### ISSUE TITLE
Scripts different from FH

### ISSUE THREAD

**Issue by StormWulf** [Ygoproco/Live#120]
I've noticed that many official cards had some issues, such as Eidos being a mandatory trigger rather than an optional trigger, and Kali Yuga negating the effects of cards played _after_ its Xyz Summon when it should only negate the effects of cards present _during_ the Xyz Summon. I suggest committing all of the scripts from FH to fix these issues and many other possible ones, while staying consistent with their fixes.

**Comment by Percival18** [comment]
Files in this repository are used in a live environment. I always need to incorporate and test all the latest core changes. Committing _all_ the scripts from FH will break stuff here.

Thanks for the suggestion.

**Comment by StormWulf** [comment]
I figured that there would be some possible utility and core conflicts with the FH branch, just so long as they can be examined and possibly resolved. In the long-run, it makes card quality easier to manage.
