### ISSUE TITLE
Many official cards still tagged Beta

### ISSUE THREAD

**Issue by StormWulf** [Ygoproco/Live#122]
Is there a particular reason why cards that have received their official card IDs are still marked as Beta? Cards from SHVI and BOSH TCG exclusives for example have been tournament legal for over two weeks.

**Comment by BowlOfPepper** [comment]
http://www.ygopro.co/Forum/tabid/95/g/posts/t/28665/BOSH-releases-are-not-updated#post136551

Quote: "Other fixes are usually more important"

Apparently there are higher priorities than updating the Beta tags for the time being.

**Comment by StormWulf** [comment]
I can understand that they dislike the grunt work involved, but I wouldn't mind clearing them myself if I knew how the Beta tags worked.

**Comment by BowlOfPepper** [comment]
Aren't they just part of the database files? Like how i used the Custom CCG tag in the past? With the tags being also hardcoded to show up in the client. I would look at it, but I don't develop anymore. Just didn't want to leave you hanging if you hadn't checked the forum.

**Comment by StormWulf** [comment]
I found out for myself that all cards not from cards.cdb or the Anime extension are marked Beta. However, there doesn't appear to be a cards.cdb in this repository. I'm unsure if it's only updated during client updates, but I could pull request a cards.cdb if that's what I should be doing with all of the Beta cards no longer marked.

**Comment by BowlOfPepper** [comment]
They wouldn't be in the cards.cdb. In the expansions/live folder, there are other .cdb files. I just looked up myself and viewed in my SQLite compare tool that the cards that should be Beta appear under prerelease.cdb.

**Comment by StormWulf** [comment]
What I meant is that even if I moved those cards over to fixot.cdb that they would still be marked Beta. Hence, everything _not_ in cards.cdb or the Anime extension are marked Beta.

**Comment by BowlOfPepper** [comment]
Did a test. Everything in that exapnsions/live folder is automatically assigned a Beta tag. This is hardcoded into YGOPro. I can speculate by disabling the Git (which may be difficult because it's compiled with YGOPro i think) that the beta cards will disappear. The reason why the Beta tag keeps appearing is because as long as the Git keeps loading the files, you can't get rid of them so they will keep being assigned the Beta tag. 

Possible Solution: Stop the Git, save the prerelease.cdb as cards.cdb, see if the Beta tag is still there. I think that would fix it.

**Comment by Steeldarkeagel** [comment]
You can turn off YgoPro reading the folder simply.
Open system.conf
Add/change to this line: ignore_instant_updates = 1
Save the file.

Cards being marked as BETA just means they are in the LIve folder, this will not be changed until the game does a major update and moves them out into the main folder.

**Comment by BowlOfPepper** [comment]
The live folder is fine, it doesn't need to be changed. Simple solution is just to edit the prerelease and remove the updated Beta cards and move them over to the official cards.cdb with their proper OCG/TCG tag. I don't know how long it would take you guys, but apparently that's all that needs done regarding the BOSH update and others. The only issue with the live folder is it not being up to date, but the overall purpose of it has been solid IMO.

**Comment by Steeldarkeagel** [comment]
As I said before adding them to the main section would require a main update, and just for the purpose of removing the tag "beta"? There is no real need, we can change from OCG only to TCG/OCG inside the live folder easily enough, it is just time consuming so requires us to have the spare time to do it.

**Comment by BowlOfPepper** [comment]
Any way for me to submit a push request/commit? I don't mind doing some database edits here and there to speed things up. Lemme know if i can.

**Comment by Zayelion** [comment]
> Any way for me to submit a push request/commit? I don't mind doing some database edits here and there to speed things up. Lemme know if i can.

With the same process we taught you at Salvation, fork the repo to your area then clone it down to your pc, do the edits, commit it and do a pull request. 

Be sure to follow contribution instructions in the readme.md file. Also to be clear the beta cards as of this iteration of YGOPro Percy cant be unmarked as beta. **You have to wait till a version update**

**Comment by BowlOfPepper** [comment]
Looks like Salvs already on it. I'll just be patient and wait like everyone else. Issue apparently is solved. Just needs to be executed now. Good Luck..

**Comment by ghost** [comment]
@Bromantic  Don't you work for Inzektorpro?

**Comment by Zayelion** [comment]
Salv isnt on anything. There is just intercommunication nowadays

**Comment by ghost** [comment]
The different ygopro teams are starting to work together which is making things go smother.

**Comment by BowlOfPepper** [comment]
@Bromantic Don't you work for Inzektorpro?

I did, but I stopped development when I realized how niche the userbase was/is. I stopped several months ago.

I just didn't want to pour any more personal time/development into what I personally felt wasn't worth it.

**Comment by Zayelion** [comment]
@Loadedtothemax stop.

**Comment by Percival18** [comment]
Done, the cards are now out of beta: 090f64457af8e7b97dcbb3053c20aef91a3bdc24

Please note that only admins can change a card to official status. Because the checkmate will have to be updated with the new cards as well.
