### ISSUE TITLE
unsych pendulum scripts...

### ISSUE THREAD

**Issue by marikisthar** [Ygoproco/Live#45]
dear perc & erie code...

![ueoehvi](https://cloud.githubusercontent.com/assets/11270664/11611390/00869356-9b80-11e5-8bc4-99b9b655badd.jpg)

your pendulum monsters script is not synch with fluoro's ones. could you update their scripts????

PS: Could you udpate all of the pendulum script in your live & anime foldr from :

"aux.AddPendulumProcedure(c)"

to

"aux.EnablePendulumAttribute(c)"

because when I combine erie's script with fluoro's one. The beta cards pendulum monster won't placed in P Zöne.

Tnx in advance

**Comment by Percival18** [comment]
This will be fixed soon.

**Comment by marikisthar** [comment]
did you update the ygopro engine to work with 2 aux lines???

besause I just tried and the same bug (error script) appered as before

![untitled](https://cloud.githubusercontent.com/assets/11270664/11923932/f4ae82f6-a75e-11e5-902f-3b305128bc1f.JPG)

ps s: I combine bothof your and fluoro's script and the same notif occured as previous version.

tnx in advance

**Comment by Percival18** [comment]
Use the utility.lua that is provided with the ygopro version you are playing on. Don't just replace files and expect it to work.
